# Generated by Django 4.0.5 on 2022-06-28 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_channel_flags_alter_channel_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='api.server'),
        ),
    ]
