# Generated by Django 4.0.5 on 2022-07-15 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_channel_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('member_id', models.BigIntegerField()),
                ('settings', models.JSONField(default=dict)),
                ('flags', models.JSONField(default=list)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.server')),
            ],
        ),
    ]
