# Generated by Django 4.0.5 on 2022-08-02 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_member_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stadium', serialize=False, to='api.server')),
                ('day', models.IntegerField(default=0)),
                ('settings', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('horses', models.JSONField(default=list)),
                ('settings', models.JSONField(default=dict)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='api.server')),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('breed', models.CharField(max_length=50)),
                ('stats', models.JSONField(default=dict)),
                ('born', models.JSONField(default=tuple)),
                ('settings', models.JSONField(default=dict)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horses', to='api.server')),
            ],
        ),
    ]
