# Generated by Django 4.0.5 on 2022-08-02 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_stadium_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horses', to='api.stadium'),
        ),
        migrations.AlterField(
            model_name='race',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='api.stadium'),
        ),
    ]
