# Generated by Django 4.0.5 on 2022-08-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='templates',
            field=models.JSONField(default=list),
        ),
    ]
