# Generated by Django 4.0.5 on 2022-08-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_member_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='events',
            field=models.JSONField(default=list),
        ),
    ]
