# Generated by Django 4.0.5 on 2022-08-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_stadium_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='flags',
            field=models.JSONField(default=list),
        ),
    ]
