# Generated by Django 4.0.5 on 2022-09-08 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_horse_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('listings', models.JSONField()),
                ('settings', models.JSONField()),
                ('channel', models.BigIntegerField()),
                ('message', models.JSONField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='api.server')),
            ],
        ),
    ]
