# Generated by Django 4.0.5 on 2022-09-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='name',
            field=models.CharField(default='Auction', max_length=50),
            preserve_default=False,
        ),
    ]
